
;; NES Registers ;;

PpuControl_2000          = $2000
PpuMask_2001             = $2001
PpuStatus_2002           = $2002
OamAddr_2003		 = $2003
PpuScroll_2005           = $2005
PpuAddr_2006             = $2006
PpuData_2007             = $2007
Sq0Duty_4000             = $4000         
Sq0Sweep_4001            = $4001 
Sq0Timer_4002            = $4002 
Sq0Length_4003           = $4003
Sq1Duty_4004             = $4004  
Sq1Sweep_4005            = $4005 
Sq1Timer_4006            = $4006 
Sq1Length_4007           = $4007
TrgLinear_4008           = $4008
NoiseVolume_400C         = $400C
NoisePeriod_400E         = $400E
NoiseLength_400F         = $400F
DmcFreq_4010             = $4010
SpriteDma_4014           = $4014
ApuStatus_4015           = $4015
Ctrl1_4016               = $4016
Ctrl2_FrameCtr_4017      = $4017

ORIGINAL		= 0
