;$9513 - data block = pilot first name ($9513-$9608) Must maintain 246 bytes - 98 bytes left
.byte B_AH,B_MOO,B_RO,$00
.byte B_B_E,B_RA,B_EE,B_T_E,$00
.byte B_SAE,B_EE,B_RA,$00
.byte B_ME,B_RA,B_EE,$00
.byte B_CA,B_EE,$00

.byte B_SHA,B_AH,$00
.byte B_RA,B_RA,B_AH,$00
.byte B_DO,B_Z_L,$00
.byte B_MA,B_K_E,B_BAE,$00
.byte B_SHA,B_RI,B_AH,B_BUL,$00

.byte B_HA,B_MAAN,$00
.byte B_FL,B_TWO,$00
.byte B_MA,B_SHU,B_MA,$00
.byte B_G_E,B_RAE,B_ME,$00
.byte B_CA,B_RA,$00

.byte B_SI,B_RO,B_CO,$00
.byte B_RO,B_JA,B_ME,B_AH,$00
.byte B_PO,B_WU,$00
.byte B_BA,B_S_E,B_K_E,$00
.byte B_RA,B_EE,B_RA,$00

.byte B_CA,B_ME,B_YOU,$00
.byte B_HAEN,B_KEN,$00
.byte B_K_E,B_WA,B_T_E,B_RO,$00
.byte B_AE,B_MA,$00
.byte B_ROO,$00

.byte B_CO,B_WU,$00
.byte B_KI,B_S_E,$00
.byte B_SI,B_NAP,B_S_E,$00
.byte B_BUR,B_NING,$00
.byte B_MON,B_SI,B_AH,$00

.byte B_ZOO,B_DO,$00
.byte B_EL,$00
.byte B_K_E,B_RI,B_S_E,$00
.byte B_SI,B_BOOK,$00
.byte B_BUR,B_NEE,$00

.byte B_GI,B_REN,$00
.byte B_KI,B_SI,B_RI,B_AH,$00
.byte B_CA,B_RO,B_JO,$00
.byte B_GA,B_TO,$00
.byte B_YA,B_JAN,$00

.byte B_AE,B_EE,B_AH,B_EE,$00

.byte $20,$c4,$20,$20,$20,$20,$b1,$20,$20,$bd,$de,$d9,$20,$de,$20,$cc
.byte $de,$d9,$20,$b0,$dd,$20,$d9,$c2,$b0,$20,$cf,$b0,$20,$d0,$b0,$20
.byte $d7,$20,$ba,$20,$b1,$20,$b3,$20,$b8,$20,$20,$d5,$20,$b9,$dd,$20
.byte $20,$20,$b0,$20,$20,$bd,$20,$df,$bd,$20,$c6,$dd,$b8,$de,$20,$b1
.byte $20,$ad,$c4,$de,$b0,$20,$df,$d9,$20,$20,$cc,$de,$af,$b8,$20,$b0
.byte $c6,$a8,$20,$da,$dd,$20,$20,$92,$9d,$20,$c4,$b0,$20,$de,$dd,$20
.byte $72,$20
