;$9513 - data block = pilot first name ($9513-$9608) Must maintain 246 bytes - 110 bytes left
.byte $36,$21,$18,$20,$00
.byte $cc,$de,$d7,$b2,$c4,$20,$00
.byte $be,$b2,$d7,$20,$00
.byte $d0,$d7,$b2,$20,$00
.byte $b6,$b2,$20,$00
.byte $bc,$ac,$b1,$20,$00
.byte $d7,$d7,$b1,$20,$00
.byte $c4,$de,$bd,$de,$d9,$20,$00
.byte $cf,$b8,$cd,$de,$20,$00
.byte $bc,$ac,$d8,$b1,$cc,$de,$d9,$20,$00
.byte $ca,$cf,$b0,$dd,$20,$00
.byte $cc,$df,$d9,$c2,$b0,$20,$00
.byte $cf,$bc,$ad,$cf,$b0,$20,$00
.byte $b8,$de,$da,$d0,$b0,$20,$00
.byte $b7,$ac,$d7,$20,$00
.byte $bc,$db,$af,$ba,$20,$00
.byte $db,$bb,$de,$d0,$b1,$20,$00
.byte $cc,$ab,$b3,$20,$00
.byte $ca,$de,$bd,$b8,$20,$00
.byte $d7,$b2,$d7,$20,$00
.byte $b6,$d0,$b0,$d5,$20,$00
.byte $cd,$dd,$b9,$dd,$20,$00
.byte $b8,$dc,$c4,$db,$20,$00
.byte $b4,$cf,$20,$00
.byte $d9,$b0,$20,$00
.byte $ba,$b3,$20,$00
.byte $b7,$b0,$bd,$20,$00
.byte $bc,$c5,$cc,$df,$bd,$20,$00
.byte $ca,$de,$c6,$dd,$b8,$de,$20,$00
.byte $d3,$dd,$bc,$b1,$20,$00
.byte $bc,$de,$ad,$c4,$de,$b0,$20,$00
.byte $cc,$df,$d9,$20,$00
.byte $b8,$d8,$bd,$20,$00
.byte $bc,$b0,$cc,$de,$af,$b8,$20,$00
.byte $ca,$de,$b0,$c6,$a8,$20,$00
.byte $b7,$de,$da,$dd,$20,$00
.byte $b7,$bc,$d8,$b1,$20,$00
.byte $83,$6f,$76,$92,$9d,$20,$00
.byte $b6,$de,$c4,$b0,$20,$00
.byte $d4,$bb,$de,$dd,$20,$00
.byte T_AE,T_EE,T_A,T_EE,$72,$20,$00
.if 0
.byte T_A,T_MU,T_RO,T_MDOT,T_RAE,T_EE,$00
.byte T_B_UE,T_RA,T_EE,T_T_E,T_MDOT,P_NO,T_A,$00
.byte T_SAE,T_EE,T_RA,T_MDOT,T_MA,T_S_E,$00
.byte T_ME,T_RA,T_EE,T_MDOT,T_YA,T_SI,T_MA,$00
.byte T_CA,T_EE,T_MDOT,T_SI,P_DAEN,$00

.byte T_SHA,T_A,T_MDOT,T_A,T_Z_E,T_NA,P_B_L,$00
.byte T_RA,T_RA,T_A,T_MDOT,P_S_N,$00
.byte T_DO,T_Z_L,T_MDOT,T_JA,T_BI,$00
.byte T_MA,T_MDOT,T_K_E,T_BAE,$00
.byte T_SHA,T_RI,T_A,T_MDOT,T_BUL,$00

.byte T_HA,T_MAN,T_MDOT,P_KAN,$00
.byte T_FL,T_TWO,$00
.byte T_MA,T_SHOE,T_MA,T_MDOT,P_JAE,T_RO,$00
.byte T_G_E,T_RAE,T_ME,T_MDOT,T_TO,T_TO,$00
.byte T_CA,T_RA,T_MDOT,P_S_N,$00

.byte P_POP,T_TEE,P_M_E,T_S_E,T_MDOT,T_SI,T_RO,T_CO,$00
.byte T_RO,T_JA,T_ME,T_A,T_MDOT,T_BI,T_DAM,$00
.byte T_PO,T_WU,T_MDOT,T_MU,T_RA,T_SA,T_MAE,$00
.byte T_BA,T_S_E,T_K_E,T_MDOT,P_OHM,$00
.byte T_RA,T_EE,T_RA,T_MDOT,T_ME,T_RA,T_MDOT,T_RA,T_EE,T_RA,$00

.byte T_CA,T_ME,T_YOU,T_MDOT,T_BI,P_DAN,$00
.byte T_HAEN,T_KEN,T_MDOT,P_BAE,P_KAE,T_NA,$00
.byte T_K_E,T_WA,T_T_E,T_RO,T_MDOT,T_BA,T_JI,T_NA,$00
.byte T_AE,T_MA,T_MDOT,P_SIN,$00
.byte T_RU,T_MDOT,T_RU,T_CA,$00

.byte T_CO,T_WU,T_MDOT,T_WU,T_RA,T_KI,$00
.byte P_CHUK,T_MDOT,T_KI,T_S_E,$00
.byte T_AE,T_EE,T_PA,T_MDOT,T_SI,T_NAP,T_S_E,$00
.byte T_SA,T_WU,T_S_E,T_MDOT,T_BUR,T_NING,$00
.byte T_BAE,T_R_E,T_NA,T_R_E,T_DO,T_MDOT,T_MON,T_SI,T_A,$00

.byte T_JU,T_DO,T_MDOT,T_A,T_SI,P_TA,$00
.byte T_EL,T_MDOT,P_PE,T_MDOT,T_FL,$00
.byte T_K_E,T_RI,T_S_E,T_MDOT,P_MAC,T_KEN,T_JI,$00
.byte T_SI,T_BOOK,T_MDOT,T_A,P_NO,$00
.byte T_BUR,T_NA,T_D_U,T_MDOT,T_WA,T_EE,T_Z_E,T_MAN,$00

.byte T_GI,T_REN,T_MDOT,T_JA,T_BI,$00
.byte T_KI,T_SI,T_RI,T_A,T_MDOT,T_JA,T_BI,$cb,$00
.byte T_CA,T_RO,T_JO,T_MDOT,T_RO,T_NA,$00
.byte T_A,T_NA,P_BELL,T_MDOT,T_GA,T_TO,$00
.byte T_YA,T_JAN,T_MDOT,T_GAE,T_BUEL,$00
.endif
