;$9609 - data block = pilot full name ($9609-$9791)
.byte P_A,P_MU,P_RO,P_MDOT,P_RAE,P_EE,$00
.byte $cc,$de,$d7,$b2,$c4,$a5,$c9,$b1,$00,$be,$b2,$d7,$a5,$cf,$bd,$00
.byte $d0,$d7,$b2,$a5,$d4,$bc,$cf,$00,$b6,$b2,$a5,$bc,$c3,$de,$dd,$00
.byte $bc,$ac,$b1,$a5,$b1,$bd,$de,$c5,$cc,$de,$d9,$00,$d7,$d7,$b1,$a5
.byte $bd,$dd,$00,$c4,$de,$bd,$de,$d9,$a5,$bb,$de,$cb,$de,$00,$cf,$a5
.byte $b8,$cd,$de,$00,$bc,$ac,$d8,$b1,$a5,$cc,$de,$d9,$00,$ca,$cf,$b0
.byte $dd,$a5,$b6,$b0,$dd,$00,$cc,$df,$d9,$c2,$b0,$00,$cf,$bc,$ad,$cf
.byte $b0,$a5,$be,$db,$00,$b8,$de,$da,$d0,$b0,$a5,$c4,$c4,$00,$b7,$ac
.byte $d7,$a5,$bd,$b0,$dd,$00,$ca,$df,$cc,$df,$c3,$cf,$bd,$a5,$bc,$db
.byte $af,$ba,$00,$db,$bb,$de,$d0,$b1,$a5,$ca,$de,$c0,$de,$d1,$00,$cc
.byte $ab,$b3,$a5,$d1,$d7,$bb,$d2,$00,$ca,$de,$bd,$b8,$a5,$b5,$d1,$00
.byte $d7,$b2,$d7,$a5,$d0,$d7,$a5,$d7,$b2,$d7,$00,$b6,$d0,$b0,$d5,$a5
.byte $cb,$de,$c0,$de,$dd,$00,$cd,$dd,$b9,$dd,$a5,$cd,$de,$af,$b9,$c5
.byte $b0,$00,$b8,$dc,$c4,$db,$a5,$ca,$de,$bc,$de,$b0,$c5,$00,$b4,$cf
.byte $a5,$bc,$b0,$dd,$00,$d9,$b0,$a5,$d9,$b6,$00,$ba,$b3,$a5,$b3,$d7
.byte $b7,$00,$c1,$ac,$af,$b8,$a5,$b7,$b0,$bd,$00,$b4,$b2,$ca,$df,$b0
;$9700
.byte $a5,$bc,$c5,$cc,$df,$bd,$00,$bb,$b3,$bd,$a5,$ca,$de,$c6,$dd,$b8
.byte $de,$00,$cd,$de,$d9,$c5,$d9,$c4,$de,$a5,$d3,$dd,$bc,$b1,$00,$bc
.byte $de,$ad,$c4,$de,$b0,$a5,$b1,$b0,$bc,$c0,$00,$b4,$d9,$a5,$cb,$df
.byte $b0,$a5,$cc,$df,$d9,$00,$b8,$d8,$bd,$a5,$cf,$af,$b9,$dd,$bc,$de
.byte $b0,$00,$bc,$b0,$cc,$de,$af,$b8,$a5,$b1,$c9,$b0,$00,$ca,$de,$b0
.byte $c6,$a8,$a5,$dc,$b2,$bd,$de,$cf,$dd,$00,$b7,$de,$da,$dd,$a5,$bb
.byte $de,$cb,$de,$00,$b7,$bc,$d8,$b1,$a5,$bb,$de,$cb,$de,$00,$83,$6f
.byte $76,$92,$9d,$00,$b1,$c5,$cd,$de,$d9,$a5,$b6,$de,$c4,$b0,$00,$d4
.byte $bb,$de,$dd,$a5,$b9,$de,$b0,$cc,$de,$d9,$00,$7e,$72,$77,$8d,$72
.byte $00
