;Must maintain 21+20 bytes - 5+8 bytes left
;$9C1C - data block ($9C1C-9C48) = TEAM COLORs
.byte B_MOO,B_PA,B_BUEL,$00
.byte B_BL,B_ROO,$00
.byte B_RAE,B_D_E,$00
.byte B_YEL,B_RO,$00
.byte B_G_E,B_RIN,$00,$98,$82,$9b,$de,$98
;$9C31 - data block ($9C31-$9C48) = Fleet 1-4 string table
.byte B_HAAM,B_DAE,B_1,$00
.byte B_HAAM,B_DAE,B_2,$00
.byte B_HAAM,B_DAE,B_3,$00
.byte B_HAAM,B_DAE,B_4,$00,$80,$72,$80,$72,$80,$72,$80,$72
