;$9B79 - data block = string ($9B79-$9B8D) No X navy
.byte $00,$03,$22,B_JAE,$24,B_HAAM,$25,B_DAE,$20,B_LTL,$3f,B_RTL,$ff,$02,$de,$23,B_HAAM,$27,$90,$28,$82
;$9B8E - data block = string - wating
.byte $00,$03
.byte $37,B_DAE,$38,B_GI,$39,B_JUNG,$ff,$3a,$4f
;$9B99 - data block = string - move done
.byte $00,$03
.byte $37,B_EE,$38,B_DONG,$39,B_JONG,$3a,B_RYO,$ff,$3a,$73,$3b,$7d,$1b,$de,$3c,$90
;$9BAC - data block = string - battling
.byte $00,$03
.byte $37,B_JEON,$38,B_TWO,$39,B_JUNG,$ff,$3a,$73,$3b,$4f
;$9BB9 - data block = string - run awaying
.byte $00,$03
.byte $37,B_DO,$38,B_ZOO,$39,B_JUNG,$ff,$3a,$6c,$3b,$78,$3c,$4f
;$9BC8 - data block = string - cannot battle
.byte $00,$03
.byte $37,B_JEON,$38,B_TWO,$39,B_BUL,$3a,B_GA,$ff,$3b,$8c,$3c,$89,$3d,$73
;$9BD9 - data block = ($9BD9-$9BF3) position: company:
.byte $00,$03
.byte $22,B_JANG,$23,B_SO,$27,B_COLON,$31,B_JUNG,$32,B_DAE,$36,B_COLON,$ff
.byte $02,$de,$24,$6e,$11,$de,$33,$73,$34,$80,$35,$72
;$9BF4 - data block = ($9BF4-$9C00) mobile armor:
.byte $00,$03
.byte $22,B_GI,$23,B_HAAM,$27,B_COLON,$3a,B_HP,$ff,$24,$9d
;$9C01 - data block = string - Mass Product mobile armor/mobile suit:
.byte $00,$03
.byte $22,B_JA,$23,B_CO,$24,B_GI,$25,B_GI,$27,B_COLON,$3a,B_MULTI,$ff,$26,$9d
;$9C12 - data block = string - Prototype mobile suit:
.byte $00,$03
.byte $22,B_SI,$23,B_JAK,$24,B_M,$25,B_S,$27,B_COLON,$3a,B_HP,$ff,$26,$53
;$9C23 - data block = string - commander : / pilot :
.byte $00,$03
.byte $20,B_MLTL,$3f,B_MRTL
.byte $22,B_HAAM,$23,B_JANG,$27,B_COLON
.byte $31,B_JO,$32,B_JONG,$33,B_SA,$36,B_COLON,$ff
.byte $25,$76,$26,$9d,$27,$3a,$11,$df,$35,$c4,$36,$3a
;$9C44 - data block = string - PL CL EX
.byte $00,$03
.byte $08,B_PL,$17,B_PL,$28,B_CL,$37,B_CL
.byte $0c,B_EX,$1b,B_EX,$2c,B_EX,$3b,B_EX,$ff
;$9C57 - data block = string - blank
.byte $00,$03
.byte $02,$00,$03,$00,$04,$00,$05,$00
.byte $22,$00,$23,$00,$24,$00,$25,$00
.byte $11,$00,$12,$00,$13,$00,$14,$00
.byte $31,$00,$32,$00,$33,$00,$34,$00,$ff
