T_NULL	= $00
T_GA	= $01

T_GI	= $07

T_DE	= $11
T_DI	= $12

T_SA	= $2D

T_EE	= $39

T_EMPTY	= $40
T_0	= $41
T_1	= $42
T_2	= $43
T_3	= $44
T_4	= $45
T_5	= $46
T_6	= $47
T_7	= $48
T_8	= $49
T_9	= $4A


T_LUTL	= $70
T_MUTL	= $71
T_RUTL	= $72
T_LDTL	= $73
T_RDTL	= $74
T_MDTL	= $75
T_LTL	= $76
T_RTL	= $77

T_JI	= $8D
T_JIN	= $8E

T_HAAM	= $9A

;----------

P_RAE	= $13
P_RO	= $15

P_MU	= $20

P_A	= $35
P_EE	= $3E

P_MDOT	= $4E
