T_NULL	= $00
T_GA	= $01
T_GYANG	= $02
T_GUN	= $03
T_GAE	= $04
T_GO	= $05
T_G_E	= $06
T_GI	= $07
T_NA	= $08
T_NAP	= $09
T_NAE	= $0A
T_NEE	= $0B
T_NING	= $0C
T_DA	= $0D
T_DAM	= $0E
T_DO	= $0F

T_DOK	= $10
T_D_U	= $11
T_DI	= $12
T_RA	= $13
T_RAE	= $14
T_RECK	= $15
T_REN	= $16
T_RO	= $17
T_RU	= $18
T_R_E	= $19
T_RI	= $1A
T_RICK	= $1B
T_MA	= $1C
T_MAN	= $1D
T_MAE	= $1E
T_MON	= $1F

T_MU	= $20
T_ME	= $21
T_BA	= $22
T_BAEK	= $23
T_BUR	= $24
T_BUEL	= $25
T_BAE	= $26
T_BEN	= $27
T_BOOK	= $28
T_BUL	= $29
T_B_UE	= $2A
T_BIG	= $2B
T_BI	= $2C
T_SA	= $2D
T_SHA	= $2E
T_SAE	= $2F

T_SOL	= $30
T_SHOE	= $31
T_S_E	= $32
T_SI	= $33
T_SIK	= $34
T_A	= $35
T_AL	= $36
T_ACK	= $37
T_OH	= $38
T_EE	= $39
T_JA	= $3A
T_Z_E	= $3B
T_CA	= $3C
T_CO	= $3D
T_K_E	= $3E
T_TO	= $3F

T_EMPTY	= $40
T_0	= $41
T_1	= $42
T_2	= $43
T_3	= $44
T_4	= $45
T_5	= $46
T_6	= $47
T_7	= $48
T_8	= $49
T_9	= $4A
T_COLON	= $4B
T_MULTI	= $4C
T_DIV	= $4D
T_MDOT	= $4E
T_DOT	= $4F

T_ALPHA	= $50
T_C	= $51
T_F	= $52
T_M	= $53
T_S	= $54
T_Z	= $55

T_TWO	= $60
T_T_E	= $61
T_TEE	= $62
T_PA	= $63

T_HEE	= $6B
T_th	= $6C

T_LUTL	= $70
T_MUTL	= $71
T_RUTL	= $72
T_LDTL	= $73
T_RDTL	= $74
T_MDTL	= $75
T_LTL	= $76
T_RTL	= $77
T_PERCENT	= $78
T_DOLLAR	= $79
T_MK2_A = $7A
T_MK2_B	= $7B
T_GP0_A	= $7C
T_GP0_B	= $7D
T_YA	= $7E
T_UH	= $7F

T_AE	= $80
T_EL	= $81
T_ON	= $82
T_WA	= $83
T_WU	= $84
T_WOON	= $85
T_ALL	= $86
T_YOU	= $87
T_JAN	= $88
T_JAM	= $89
T_JO	= $8A
T_JU	= $8B
T_Z_L	= $8C
T_JI	= $8D
T_JIN	= $8E
T_JIL	= $8F

T_KEN	= $90
T_KU	= $91
T_QUEEN	= $92
T_QU	= $93
T_KI	= $94
T_TAN	= $95
T_PO	= $96
T_F_E	= $97
T_FL	= $98
T_HA	= $99
T_HAAM	= $9A
T_HAEN	= $9B
T_HWA	= $9C

T_NT	= $B4
T_PL	= $B5
T_CL	= $BA
T_EX	= $BB

;---------- pilot full name tile($23800 bottom part)

P_GAE	= $9D
P_NO	= $9E
P_DAN	= $9F

P_DAE	= $A0
P_DAEN	= $A1
P_RYO	= $A2
P_MAC	= $A3
P_M_E	= $A4
P_BELL	= $A5
P_B_L	= $A6
P_S_N	= $A7
P_SIN	= $A8
P_OHM	= $A9
P_WOL	= $AA
P_JANG	= $AB
P_JEON	= $AC
P_JAE	= $AD
P_JONG	= $AE
P_JOONG	= $AF

P_CHI	= $B0
P_KAN	= $B1
P_KAE	= $B2
P_TA	= $B3

P_POP	= $B6

P_PE	= $BC
P_NUENG	= $BD
P_DONG	= $BE
P_BAE	= $BF

P_BOO	= $C0
P_JAK	= $C1
P_HAENG	= $C2
P_CHUK	= $C3
