B_NULL	= $00
B_NING	= $01
B_REN	= $02
B_MAAN	= $03
B_MON	= $04
B_BOOK	= $05
B_BUL	= $06
B_EL	= $07
B_JAN	= $08
B_Z_L	= $09
B_KEN	= $0A
B_GA	= $0B
B_GYANG	= $0C
B_GUN	= $0D
B_GE	= $0E
B_GO	= $0F

B_G_E	= $10
B_GI	= $11
B_NA	= $12
B_NAP	= $13
B_NAE	= $14
B_NEE	= $15
B_DA	= $16
B_DAM	= $17
B_DO	= $18
B_DOG	= $19
B_D_E	= $1A
B_DI	= $1B
B_RA	= $1C
B_RAE	= $1D
B_RECK	= $1E
B_RO	= $1F

B_ROO	= $20
B_R_E	= $21
B_RI	= $22
B_RICK	= $23
B_MA	= $24
B_MAE	= $25
B_MOO	= $26
B_ME	= $27
B_BA	= $28
B_BAG	= $29
B_BUR	= $2A
B_BUEL	= $2B
B_BE	= $2C
B_BEN	= $2D
B_B_E	= $2E
B_BI	= $2F

B_BIG	= $30
B_SA	= $31
B_SHA	= $32
B_SOL	= $33
B_S_E	= $34
B_SI	= $35
B_AH	= $36
B_ACK	= $37
B_OH	= $38
B_EE	= $39
B_JA	= $3A
B_Z_E	= $3B
B_CA	= $3C
B_CO	= $3D
B_K_E	= $3E
B_TO	= $3F

B_EMPTY	= $40
B_0	= $41
B_1	= $42
B_2	= $43
B_3	= $44
B_4	= $45
B_5	= $46
B_6	= $47
B_7	= $48
B_8	= $49
B_9	= $4A
B_COLON	= $4B
B_MULTI	= $4C
B_DIV	= $4D
B_MDOT	= $4E
B_DOT	= $4F

B_ALPHA	= $50
B_C	= $51
B_F	= $52
B_M	= $53
B_S	= $54
B_Z	= $55

B_TWO	= $60
B_T_E	= $61
B_TEE	= $62
B_PA	= $63

B_HE	= $6B
B_th	= $6C
B_V	= $6D

B_LUTL	= $70
B_MUTL	= $71
B_RUTL	= $72
B_LDTL	= $73
B_RDTL	= $74
B_MDTL	= $75
B_LTL	= $76
B_RTL	= $77

B_USD	= $79
B_MK2_A = $7A
B_MK2_B	= $7B
B_GP0_A	= $7C
B_GP0_B	= $7D
B_YA	= $7E
B_UH	= $7F

B_AE	= $80
B_ON	= $81
B_WA	= $82
B_WU	= $83
B_WOON	= $84
B_WOOL	= $85
B_YOU	= $86
B_JAM	= $87
B_JO	= $88
B_JU	= $89
B_JI	= $8A
B_JIN	= $8B
B_JIL	= $8C
B_QOO	= $8D
B_QUEEN	= $8E
B_QUE	= $8F

B_KI	= $90
B_TAN	= $91
B_PO	= $92
B_F_E	= $93
B_FL	= $94
B_HA	= $95
B_HAAM	= $96
B_HAEN	= $97
B_HWA	= $98
B_SAE	= $99
B_SHU	= $9A
B_SICK	= $9B
B_AL	= $9C
B_GAE	= $9D
B_DAE	= $9E
B_DONG	= $9F

B_DOE	= $A0
B_RYUNG	= $A1
B_RYO	= $A2
B_LL	= $A3
B_RIN	= $A4
B_MYUNG	= $A5
B_BAE	= $A6
B_BO	= $A7
B_BOO	= $A8
B_BL	= $A9
B_SAN	= $AA
B_SANG	= $AB
B_SAENG	= $AC
B_SO	= $AD
B_QST	= $AE
B_SPZ	= $AF

B_I	= $B0
B_II	= $B1
B_III	= $B2
B_IIII	= $B3
B_SOO	= $B6

B_SEUP	= $BC
B_SEUNG	= $BD
B_UP	= $BE
B_UT	= $BF

B_YEL	= $C0
B_WOL	= $C1
B_UI	= $C2
B_IP	= $C3
B_JAK	= $C4
B_JANG	= $C5
B_JEON	= $C6
B_JEOM	= $C7
B_JAE	= $C8
B_JONG	= $C9
B_ZOO	= $CA
B_JUNG	= $CB
B_CHI	= $CC
B_TURN	= $CD
B_TEAM	= $CE
B_HAL	= $CF

B_HAP	= $D0



;---------- top name tile($20000 top part)

T_NULL	= $00
T_GA	= $01
T_GYANG	= $02
T_GUN	= $03
T_GAE	= $04
T_GO	= $05
T_G_E	= $06
T_GI	= $07
T_NA	= $08
T_NAP	= $09
T_NAE	= $0A
T_NEE	= $0B
T_NING	= $0C
T_DA	= $0D
T_DAM	= $0E
T_DO	= $0F

T_DOK	= $10
T_D_U	= $11
T_DI	= $12
T_RA	= $13
T_RAE	= $14
T_RECK	= $15
T_REN	= $16
T_RO	= $17
T_RU	= $18
T_R_E	= $19
T_RI	= $1A
T_RICK	= $1B
T_MA	= $1C
T_MAN	= $1D
T_MAE	= $1E
T_MON	= $1F

T_MU	= $20
T_ME	= $21
T_BA	= $22
T_BAEK	= $23
T_BUR	= $24
T_BUEL	= $25
T_BAE	= $26
T_BEN	= $27
T_BOOK	= $28
T_BUL	= $29
T_B_UE	= $2A
T_BI	= $2B
T_BIG	= $2C
T_SA	= $2D
T_SHA	= $2E
T_SAE	= $2F

T_SOL	= $30
T_SHOE	= $31
T_S_E	= $32
T_SI	= $33
T_SIK	= $34
T_A	= $35
T_AL	= $36
T_ACK	= $37
T_OH	= $38
T_EE	= $39
T_JA	= $3A
T_Z_E	= $3B
T_CA	= $3C
T_CO	= $3D
T_K_E	= $3E
T_TO	= $3F

T_EMPTY	= $40
T_0	= $41
T_1	= $42
T_2	= $43
T_3	= $44
T_4	= $45
T_5	= $46
T_6	= $47
T_7	= $48
T_8	= $49
T_9	= $4A
T_COLON	= $4B
T_MULTI	= $4C
T_DIV	= $4D
T_MDOT	= $4E
T_DOT	= $4F

T_ALPHA	= $50
T_C	= $51
T_F	= $52
T_M	= $53
T_S	= $54
T_Z	= $55

T_MLTL	= $5A
T_MMTL	= $5B
T_MRTL	= $5C

T_TWO	= $60
T_T_E	= $61
T_TEE	= $62
T_PA	= $63

T_HEE	= $6B
T_th	= $6C

T_LUTL	= $70
T_MUTL	= $71
T_RUTL	= $72
T_LDTL	= $73
T_RDTL	= $74
T_MDTL	= $75
T_LTL	= $76
T_RTL	= $77
T_PERCENT	= $78
T_DOLLAR	= $79
T_MK2_A = $7A
T_MK2_B	= $7B
T_GP0_A	= $7C
T_GP0_B	= $7D
T_YA	= $7E
T_UH	= $7F

T_AE	= $80
T_EL	= $81
T_ON	= $82
T_WA	= $83
T_WU	= $84
T_WOON	= $85
T_ALL	= $86
T_YOU	= $87
T_JAN	= $88
T_JAM	= $89
T_JO	= $8A
T_JU	= $8B
T_Z_L	= $8C
T_JI	= $8D
T_JIN	= $8E
T_JIL	= $8F

T_KEN	= $90
T_KU	= $91
T_QUEEN	= $92
T_QU	= $93
T_KI	= $94
T_TAN	= $95
T_PO	= $96
T_F_E	= $97
T_FL	= $98
T_HA	= $99
T_HAAM	= $9A
T_HAEN	= $9B
T_HWA	= $9C

T_NT	= $B4
T_PL	= $B5
T_CL	= $BA
T_EX	= $BB

;---------- pilot full name tile($23800 bottom part)

P_GAE	= $9D
P_NO	= $9E
P_DAN	= $9F

P_DAE	= $A0
P_DAEN	= $A1
P_RYO	= $A2
P_MAC	= $A3
P_M_E	= $A4
P_BELL	= $A5
P_B_L	= $A6
P_S_N	= $A7
P_SIN	= $A8
P_OHM	= $A9
P_WOL	= $AA
P_JANG	= $AB
P_JEON	= $AC
P_JAE	= $AD
P_JONG	= $AE
P_JOONG	= $AF

P_CHI	= $B0
P_KAN	= $B1
P_KAE	= $B2
P_TA	= $B3

P_POP	= $B6

P_PE	= $BC
P_NUENG	= $BD
P_DONG	= $BE
P_BAE	= $BF

P_BOO	= $C0
P_JAK	= $C1
P_HAENG	= $C2
P_CHUK	= $C3
